version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_local
    restart: unless-stopped
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
